### ISSUE TITLE
Make on Windows

### ISSUE THREAD

**Issue by mulderp** [LimiFrog/LimiFrog-SW#1]
Hi,

not critical, but I did a quick check on a Windows PC with a toolchain similar to:

http://www.ba0sh1.com/opensource-stm32-development

What I get after running make is:

```
C:\Users\mpaa\embedded\LimiFrog-SW\projects\LimiFrog-BringUp-0>make
The syntax of the command is incorrect.
make: *** [obj/startup_stm32l476xx.o] Error 1
```

**Comment by LimiFrog** [comment]
Hi Patrick,
yes the Makefile has been running on Linux but needs some update to run on Windows.
Some trials were made some time ago using the OpenSTM32 System Workbench (http://www.openstm32.org/System+Workbench+for+STM32) which relies on gcc and runs on Windows. As far as I remember Windows doesn't like the "mkdir" command, it had to be removed.

**Comment by LimiFrog** [comment]
I have fixed the Makefiles for Windows, with a check on the (tool chain's) OS being used. 
Also modified the names of rules when using Windows to make them more in line with Eclipse default expectations. Next step may be to adopt consistent rules naming for both OS.

**Comment by mulderp** [comment]
Thanks!
Works nicely now.
Btw, just to confirm I used gcc 4.9 on Windows 7.
