### ISSUE TITLE
Rename BriefDesc.txt --> README.md

### ISSUE THREAD

**Issue by mulderp** [LimiFrog/LimiFrog-SW#2]
Hi,

if you rename BriefDesc.txt to README.md, Github automatically shows the content of the file under the project. This might be nice to have for the bringup examples.

**Comment by LimiFrog** [comment]
Indeed. I plan a major update of the database, I'll squeeze that change in.

**Comment by LimiFrog** [comment]
Done. (ReadMe.txt, opens automatically under GitHub).
